### ISSUE TITLE
Install a file identifying image

### ISSUE THREAD

**Issue by bdilly** [solettaproject/meta-soletta#15]
Maybe hashes of soletta and soletta-dev-app or meta-soletta tag could be enough for us to help to support users and QA (so we're sure what versions are they using).

**Comment by anselmolsm** [comment]
+1

**Comment by brunobottazzini** [comment]
PR opened, implementing the hash for soletta so far: https://github.com/solettaproject/meta-soletta/pull/17

**Comment by bdilly** [comment]
OK, pr was merged. Issue can be closed.
Thanks
