### ISSUE TITLE
remove systemd bbappend

### ISSUE THREAD

**Issue by mythi** [solettaproject/meta-soletta#31]
I'm tempted to send a pull request to remove systemd bbappend but I thought to file an issue first to discuss it through.

The problems I'm currently seeing with this is:
- udev's built-in blkid is important for systems relying on /dev/disk/by-\* symlinks
- additional .service files can be added in an independent recipe/.bb instead of doing it in a systemd bbappend

Is there a dependency to have blkid disabled when automount service is used?

**Comment by barbieri** [comment]
no, it was only used to reduce binary size.

**Comment by brunobottazzini** [comment]
As far as I remember, this bbappend was also used to autostart some custom created services for Minnowboard only. 

For instance: 
     - Autostart an eth0 interface
     - Automount a pendrive
     - Warn the device booted by turning off a led etc.

For Edison and Galileo, I have created a non official branches for it. 

We were discussing what to do with them, if we would merge everything or split the branches for each devices. We haven't reached a conclusion of it.

**Comment by mythi** [comment]
On Mon, Jan 11, 2016 at 6:27 PM, Bruno Bottazzini  wrote:

> As far as I remember, this bbappend was also used to autostart some non
> custom created services for Minnowboard only.
> 
> For instance:
> - Autostart an eth0 interface
> - Automount a pendrive
> - Warn the device booted by turning of a led etc.
> 
> My feedback was these don't have to (nor should) be in a systemd bbappend.
> They are not appending systemd but the demo image.

Is the binary size requirement a hard requirement or can we proceed with
systemd bbappend removal?

**Comment by barbieri** [comment]
no hard requirement, you can remove it.
