### ISSUE TITLE
[soletta] QA issue on 1_beta19

### ISSUE THREAD

**Issue by chongyic** [solettaproject/meta-soletta#82]
There are error on bad RPATH at do_package_qa.

Please refer to error message below.

`ERROR: soletta-1_beta19+gitAUTOINC+6a7bc32376-r0 do_package_qa: QA Issue: package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/accelerometer.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/oauth.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/process.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/file.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/test.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/mqtt.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/http-server.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/gyroscope.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/am2315.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/oic.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/twitter.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/evdev.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/power-supply.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/udev.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/piezo-speaker.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/flower-power.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/led-strip.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/network.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/thingspeak.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/location.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/json.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/persistence.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/stts751.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/update.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/iio.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/max31855.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/magnetometer.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/servo-motor.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/unix-socket.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/grove.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/form.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/compass.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/http-client.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/calamari.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/keyboard.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/js.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/http-composed-client.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/http-composed-server.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-galileo-rev-d.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-galileo-rev-g.so
package soletta-dev contains bad RPATH /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/git/build/soletta_sysroot/usr/lib in file /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-edison-rev-c.so [rpaths]
ERROR: soletta-1_beta19+gitAUTOINC+6a7bc32376-r0 do_package_qa: QA Issue: -dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/accelerometer.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/oauth.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/process.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/file.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/test.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/mqtt.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/http-server.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/gyroscope.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/am2315.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/oic.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/twitter.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/evdev.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/power-supply.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/udev.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/piezo-speaker.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/flower-power.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/led-strip.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/network.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/thingspeak.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/location.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/json.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/persistence.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/stts751.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/update.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/iio.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/max31855.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/magnetometer.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/servo-motor.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/unix-socket.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/grove.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/form.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/compass.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/http-client.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/calamari.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow/keyboard.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/js.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/http-composed-client.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/flow-metatype/http-composed-server.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-galileo-rev-d.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-galileo-rev-g.so'
-dev package contains non-symlink .so: soletta-dev path 'work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/packages-split/soletta-dev/usr/lib/soletta/modules/pin-mux/intel-edison-rev-c.so' [dev-elf]
WARNING: soletta-1_beta19+gitAUTOINC+6a7bc32376-r0 do_package_qa: QA Issue: /usr/lib/soletta/ptest/run-ptest contained in package soletta-ptest requires /bin/bash, but no providers found in RDEPENDS_soletta-ptest? [file-rdeps]
ERROR: soletta-1_beta19+gitAUTOINC+6a7bc32376-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: soletta-1_beta19+gitAUTOINC+6a7bc32376-r0 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /home/ilab/yocto/poky/build/tmp/work/corei7-64-smallos-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/log.do_package_qa.23865
ERROR: Task 12 (/home/ilab/yocto/meta-soletta/recipes-soletta/soletta/soletta_git.bb, do_package_qa) failed with exit code '1'`

**Comment by brunobottazzini** [comment]
I just detect this issue here..

Did you guys make a workaround for this problem ?

I'm looking into the solution of the issue and I will get back to you asap 

Thanks!

**Comment by brunobottazzini** [comment]
@chongyic,

I have created  PR fixing this error: https://github.com/solettaproject/meta-soletta/pull/86

Could you review it ?

**Comment by chongyic** [comment]
@brunobottazzini @lblim
We had a workaround where we try skipping the QA for rpath but your solution would be a better one.
Tested your fix and it does not show any error.
Thank you.

**Comment by brunobottazzini** [comment]
@chongyic thanks patch merged
