### ISSUE TITLE
[soletta] intermittent failure on nodejs 

### ISSUE THREAD

**Issue by chongyic** [solettaproject/meta-soletta#83]
There are intermittent failure on build where nodejs is not compiled prior soletta being compiled.
Adding nodejs-native to DEPENDS will fix the issue.

Please refer to error message below:

`| DEBUG: Executing shell function do_compile
| /home/ilab/dev/yocto-git/yocto_build/build/tmp/work/corei7-64-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/run.do_compile.25349: line 107: npm: command not found
| WARNING: /home/ilab/dev/yocto-git/yocto_build/build/tmp/work/corei7-64-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/run.do_compile.25349:1 exit 127 from
|   npm config set dev false
| ERROR: Function failed: do_compile (log file is located at /home/ilab/dev/yocto-git/yocto_build/build/tmp/work/corei7-64-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/log.do_compile.25349)
`

**Comment by brunobottazzini** [comment]
Hello @chongyic, I have created and tested this patch: https://github.com/solettaproject/meta-soletta/pull/85

Could you verify if this intermittent issue is resolved ?

**Comment by brunobottazzini** [comment]
@chongyic were you able to verify if the patch solves this issue ?

**Comment by chongyic** [comment]
Hi @brunobottazzini , I did not see any issue after the patch.
Thanks.

**Comment by brunobottazzini** [comment]
@chongyic, patch merged and issue closed.

Thanks...
