### ISSUE TITLE
soletta_git.bb + package strip/split

### ISSUE THREAD

**Issue by pohly** [solettaproject/meta-soletta#88]
The following commit in OE-core breaks compilation of Soletta in Ostro OS (https://ostroproject.org/jenkins/job/build_intel-corei7-64/1799/console) because source code now gets split off without getting packaged:

```
commit 9b6457279b5a650ccb695ee6ff19d3f675bfca6f
Author: Stephano Cetola <stephano.cetola@linux.intel.com>
Date:   Thu May 26 13:40:37 2016 -0700

    package.bbclass: fix strip and split logic

    In order for strip and split to work together, we need to populate the
    data structors if either split OR strip are not inhibited.

    Original behaviour:

    INHIBIT_PACKAGE_STRIP: no strip, no debug split
    INHIBIT_PACKAGE_DEBUG_SPLIT: strip, no split

    Behaviour after this patch:

    INHIBIT_PACKAGE_STRIP: no strip, debug split
    INHIBIT_PACKAGE_DEBUG_SPLIT: strip, no split
    BOTH: no strip, no split, DNP data structures

    (From OE-core rev: 0df6dabdf0a61ae7b99c6a792f1eec754a7b23bd)

    Signed-off-by: Stephano Cetola <stephano.cetola@linux.intel.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
```

INHIBIT_PACKAGE_STRIP=1 is used in the recipe, so the intended behavior is "no strip, no debug split"? Or was that just a workaround that can be removed or needs to be done differently with latest OE-core master?

**Comment by barbieri** [comment]
@brunobottazzini can you comment, I believe it was a workaround and we shouldn't force any of those.

**Comment by brunobottazzini** [comment]
@pohly, @barbieri, Indeed, it was a workaround and It can be removed. 

I am going to run some tests here and propose this PR for meta-soletta asap.
