### ISSUE TITLE
Soletta fails to compile during generic Yocto build for Edison (non Ostro)

### ISSUE THREAD

**Issue by js333031** [solettaproject/meta-soletta#91]
generic_yocto/out/linux64/build/tmp/work/core2-32-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/log.do_compile.29481
....

ERROR: Function failed: do_compile (log file is located at /media/development/edison/yocto/generic_yocto/out/linux64/build/tmp/work/core2-32-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/log.do_compile.29481)
ERROR: Logfile of failure stored in: /media/development/edison/yocto/generic_yocto/out/linux64/build/tmp/work/core2-32-poky-linux/soletta/1_beta19+gitAUTOINC+6a7bc32376-r0/temp/log.do_compile.29481
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 -e MAKEFLAGS= CFLAGS=--sysroot=/media/development/edison/yocto/generic_yocto/out/linux64/build/tmp/sysroots/edison -pthread -lpcre TARGETCC=i586-poky-linux-gcc  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -mstackrealign -fno-omit-frame-pointer --sysroot=/media/development/edison/yocto/generic_yocto/out/linux64/build/tmp/sysroots/edison TARGETAR=i586-poky-linux-ar
|     INST   build/soletta_sysroot/usr/include/soletta/sol-util.h

<snip>

|      GEN   build/soletta_sysroot/usr/include/soletta/sol-flow-buildopts.h
| Ignoring oic.r.sensor.geolocation.json due to exception in generator. Traceback follows:
| Traceback (most recent call last):
|   File "./data/scripts/sol-oic-gen.py", line 1719, in <module>
|     json_name):
|   File "./data/scripts/sol-oic-gen.py", line 989, in generate_for_schema
|     j = load_json_schema(directory, path)
|   File "./data/scripts/sol-oic-gen.py", line 69, in load_json_schema
|     doc = props.get('description', '')
| AttributeError: 'str' object has no attribute 'get'

<snip>

**Comment by js333031** [comment]
I still see the issue. I did a 'bitbake -c cleansstate soletta && bitbake soletta'

Please verify if I used the right proposed fix:
$ ls -l /lib64/ld-linux-x86-64.so.2  /lib/ld-linux-x86-64.so.2
lrwxrwxrwx 1 root root     32 May 26 06:32 /lib64/ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-2.15.so
-rwxr-xr-x 1 root root 149280 Jun  9 09:33 /lib/ld-linux-x86-64.so.2
$

**Comment by brunobottazzini** [comment]
Hello @js333031,

After some time trying to figure out the problem I just realized that the python version of the generic Yocto Edison is the version 3.3 and Soletta requires the version at least 3.4.

See the documentation here: https://github.com/solettaproject/soletta/wiki/Build-requirements

If you want to proceed to fix this problem you should upgrade the python3 version.

Still, we highly recommend you to use Ostro OS, the build would be the easier and you can customize it as it was Yocto, since Ostro is Yocto based.
