### ISSUE TITLE
mqtt_basic.fbp unable to connect to host if using mosquitto 1.4.0

### ISSUE THREAD

**Issue by laykuanloon** [solettaproject/meta-soletta#93]
I encountered "WRN:sol-mqtt ./src/lib/comms/sol-mqtt-impl-mosquitto.c:412 sol_mqtt_connect() Unable to connect to" when I run the mqtt_basic.fbp with mosquitto 1.4.0

After I manually patch the following 1 patch into mosquitto 1.4.0 then mqtt_basic.fbp works. 
- https://github.com/eclipse/mosquitto/commit/8de6b92e3c20dda55eb650c48bbcc775e7d229ef
  "Fix calls to mosquitto_connect*_async() not completing."

The specific patch is in mosquitto version 1.4.2 - 20150507release. 
- http://mosquitto.org/ChangeLog.txt

Please check whether the patch is OK, without affect any other mosquitto function. Or I should update the mosquitto from version 1.4.0 to version 1.4.2 ?

**Comment by barbieri** [comment]
should be right, but I guess it's better for us to require the newer version where the patch is already integrated.

**Comment by bdilly** [comment]
For now we don't check for mosquitto version because they don't provide pkg-config files.
I believe they're working on it now:

https://github.com/eclipse/mosquitto/pull/213

When that get merged we could check for versions > 1.4.2

**Comment by yongli3** [comment]
@fulong82 @laykuanloon it seems to me that the above eclipse/mosquitto#213 ware merged, is it okay to close this issue?

**Comment by ceolin** [comment]
unfortunatelly it was merged on develop branch (and it is not on master). I'll fix it in soletta using a different solution.

**Comment by ceolin** [comment]
@fulong82 @laykuanloon @yongli3 https://github.com/solettaproject/soletta/pull/2317

**Comment by peijiajames** [comment]
@laykuanloon as the fix is already merged in, could you please help to check and close the issue if the fix is valid? Thanks.
