### ISSUE TITLE
Request update Build-Requirements wiki page

### ISSUE THREAD

**Issue by fulong82** [solettaproject/meta-soletta#94]
Hi @barbieri, @bdilly,

We are building soletta using Jethro Yocto build package. We used to build the Soletta successfully before when we pull v1_beta19 version. But when we pull with latest meta-soletta & soletta source and commit id, we are no longer able to build successfully. Cross check with Ostro-os v1.0.0 and @yongli3 who built successfully with Ostro, we found that the python3 version is 3.5.1 whereas Jethro Yocto is 3.4.3. If according to the [Build-requirements](https://github.com/solettaproject/soletta/wiki/Build-requirements) wiki page, python3 is required 3.4 and above and our build system should not be a problem. So, the latest Soletta source seem to be not in this case. So we would like to request an update to the wiki page for [Build-requirements & dependency](https://github.com/solettaproject/soletta/wiki/Build-requirements) in order for us to enable the correct build environment for our system.

Thanks & Regards,
Wilson

**Comment by glima** [comment]
- Wilson Kweh notifications@github.com [2016-06-30 01:31:58 -0700]:

> Hi @barbieri, @bdilly,
> 
> We are building soletta using Jethro Yocto build package. We used to build the Soletta successfully before when we pull v1_beta19 version. But when we pull with latest meta-soletta & soletta source and commit id, we are no longer able to build successfully. Cross check with Ostro-os v1.0.0 and @yongli3 who built successfully with Ostro, we found that the python3 version is 3.5.1 whereas Jethro Yocto is 3.4.3. If according to the [Build-requirements](https://github.com/solettaproject/soletta/wiki/Build-requirements) wiki page, python3 is required 3.4 and above and our build system should not be a problem. So, the latest Soletta source seem to be not in this case. So we would like to request an update to the wiki page for [Build-requirements & dependency](https://github.com/solettaproject/soletta/wiki/Build-requirements) in order for us to enable the correct build environment for our system.

Hi, Kweh.

Could you please paste your error output before we can evaluate that need?
We can't proceed without knowing exactly what you got as issue.

Thanks.

> Thanks & Regards,
> Wilson
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/solettaproject/meta-soletta/issues/94

## 

Gustavo Lima Chaves
Intel - Open Source Technology Center

**Comment by fulong82** [comment]
Hi @laykuanloon, could you please help to provide the build error log here? Thanks.

Regards,
Wilson

**Comment by laykuanloon** [comment]
Hi, I able to build without error when using latest commit 2dd375cd516587c54db2f203656f6adc5c6e08f2 
Previous error is happen in 5d3313a09ec66f09dc2948cca20cceeae4b4522e

**Comment by glima** [comment]
Closing issue, then. Thanks.
